### User registration
POST http://localhost:8000/user-api/user
Content-Type: application/json

{
    "name":"test1",
    "email":"test1@gmail.com",
    "password":"test1",
    "todos":[]
}

### User login
POST http://localhost:8000/user-api/login
Content-Type: application/json

{
    "email":"test1@gmail.com",
    "password":"test1"   
}


### Add task
PUT http://localhost:8000/user-api/todo/userId
Content-Type: application/json

{
    "taskName":"sleeping",
    "description":"I sleep early on this day"   
}




### Edit task
PUT http://localhost:8000/user-api/edit-todo/userid/100/taskid/200
Content-Type: application/json

{
    "taskName":"sleeping again",
    "description":"I sleep early on this day"   
}

### Set task completed
PUT http://localhost:8000/user-api/edit-status/userid/100/taskid/200
Content-Type: application/json

{
    "taskName":"sleeping again",
    "description":"I sleep early on this day",
    "status":"completed"   
}


### Delete task
PUT http://localhost:8000/user-api/delete-todo/userid/100/taskid/200
Content-Type: application/json

{
   
}
